quarkus.http.port=8085

# all-resources is a custom resource collection name
quarkus.http.auth.permission.all-resources.paths=/*
quarkus.http.auth.permission.all-resources.policy=authenticated

# indicates Authorization Code Flow
quarkus.oidc.application-type=web_app
# invalidates the active session when called
quarkus.oidc.logout.path=/logout
